### PR TITLE
Bugfix/137 fix break on project names

### PR DESCRIPTION
**Pull request by Keilaron**
More fixes as discussed in #139. 

If the select doesn't retain its selection as previously observed, then I can reverse some of the changes (namely usage of `.html()` for the contents) and that should allow it to retain its selection.

### CODE REVIEW

**Comment by netwolfuk** [comment]
BTW, I was updating the select at the end, in case it takes a second or so to update the 100 items.

**Comment by Keilaron** [comment]
That's a good point, but 100 items shouldn't pose a problem.

**Comment by netwolfuk** [comment]
true

**Comment by netwolfuk** [comment]
Good news, the checkbox and select are now working perfectly in `editWebhook.js`.

Can you please take a look at the template edit js as well?

**Comment by netwolfuk** [comment]
To be more specific, the selects within the preview dialog.

**Comment by Keilaron** [comment]
I'm not sure what you mean. I wrote fixes for those too. Are the options still not showing up?

**Comment by Keilaron** [comment]
What about them? I'm interpreting from your previous comment that you mean the select that had its options go missing is now working, right?

**Comment by netwolfuk** [comment]
https://github.com/tcplugins/tcWebHooks/blob/1.1.x.x-js-fixes/tcwebhooks-web-ui/src/main/resources/buildServerResources/WebHook/js/editWebhookTemplate.js#L475

**Comment by netwolfuk** [comment]
Yeah. You've fixed the missing items in the webhook preview dialog. However there is similar code which allows previewing template changes too.

**Comment by Keilaron** [comment]
By the way.. what's with the `Webhook\index.jsp` file, is that generated? It seems to have duplicate code.

**Comment by netwolfuk** [comment]
It was the original code inlined in the page. About a year ago it moved to the .js file. I think it's unused, except maybe on the first page load. 

Perhaps, if you're not sick of helping me we could look at that after we have released these changes.

If should be as simple as breakpointing it and checking if it runs.

**Comment by Keilaron** [comment]
I can't check anything on my company's TC for a little while, I'm afraid, but it shouldn't be too difficult to figure out if you can rip out all the JS code, really.

**Comment by netwolfuk** [comment]
Yep. Understood. Your help so far had been invaluable. Thank you. As you probably guessed, js is not my forte.

**Pull request merged**
