### PR TITLE
Add Discord Webhooks

### PR DESCRIPTION
**Pull request by features-not-bugs**
As per the title, I've added the Discord Webhook templates to generate an embed styled message.

The template is mostly copied from the Slack Json template.

I think I've setup the test appropriately, although I am unfamiliar with java based environments. 
I'd appreciate it if someone could confirm that the changes made are indeed correct.

Sample Output for a non branch aware build
image

### CODE REVIEW

**Comment by netwolfuk** [comment]
Hi @features-not-bugs, thanks so much for taking the time to put this together.

I just had a quick look over this on my phone, it looks pretty good. I have a few comments on the testing, but I think that they are mostly my fault. I'll comment on them when I get a chance to get to a computer.

Thanks!

**Comment by netwolfuk** [comment]
Also, I can't see an entry in the build server plugin webhook listener XML file.

The class needs to be added there so that spring loads it. 

For some reason I can't copy the correct name of the file in my phone. It's within the UI section of the plugin code (don't ask 😉)

**Comment by features-not-bugs** [comment]
Hi @netwolfuk,

No worries regarding the tests, I haven't used java all that much let alone any of it's testing functionality.

I've added the Discord XML Template to the Spring configuration file.

Let me know if there's anything else.

Cheers!

**Comment by netwolfuk** [comment]
HI @features-not-bugs  I have merged your code and fixed a test. You can download a build from 
[here](https://teamcity.jetbrains.com/buildConfiguration/WebHooksAndOtherPlugins_TcWebHooks?branch=issue_136-add_discord_webhooks&buildTypeTab=overview) (just login as a guest)

**Comment by netwolfuk** [comment]
BTW, do you know about this? https://github.com/tcplugins/tcWebHooksTemplates

**Comment by features-not-bugs** [comment]
Hi @netwolfuk

Just downloaded the build artifact, it seems to be working well! Cheers!

I just had a quick look at that, it's a great addition!

**Comment by netwolfuk** [comment]
Great. Thanks for the feedback. 

I don't have an ETA for 1.2.x release yet. There's a lot to do yet, but the alpha's should be pretty stable.

**Comment by netwolfuk** [comment]
Sorry. I forgot to say, thank you so much for taking the time to do the code and raise the PR. It's really terrific.

**Comment by features-not-bugs** [comment]
No worries! Cheers.

**Comment by netwolfuk** [comment]
Released in https://github.com/tcplugins/tcWebHooks/releases/tag/v1.2.0-alpha.2

**Pull request merged**
